"""Render a daily research report as PDF.

Pure-Cowork architecture: this runs in the same Cowork session as the daily
scan, just at the end. Reads findings + digest text, writes one PDF per run.

Library: fpdf2 (pure Python, single dependency, no Cairo / no LaTeX / no pandoc).
"""
from __future__ import annotations

from datetime import date
from pathlib import Path

from fpdf import FPDF


def _safe_text(s) -> str:
    """fpdf2's helvetica is Latin-1 only. Replace characters that would break it."""
    if s is None:
        return ""
    s = str(s)
    replacements = {
        "—": "-", "–": "-",     # em / en dash
        "−": "-",                     # minus sign
        "‘": "'", "’": "'",     # smart quotes
        "“": '"', "”": '"',
        "…": "...",                   # ellipsis
        "·": "*", "•": "*",     # bullets
        " ": " ",                     # nbsp
        "≡": "=", "≈": "~",     # math
        "→": "->", "←": "<-",
        "×": "x", "±": "+/-",
        "α": "alpha", "β": "beta", "γ": "gamma",
        "λ": "lambda", "σ": "sigma", "π": "pi", "μ": "mu",
        "≤": "<=", "≥": ">=",
    }
    for k, v in replacements.items():
        s = s.replace(k, v)
    # Final pass: anything still non-Latin-1 becomes '?'
    return s.encode("latin-1", errors="replace").decode("latin-1")


class _Report(FPDF):
    def __init__(self, scan_date: str):
        super().__init__(format="letter")
        self.scan_date = scan_date
        self.set_margins(left=18, top=20, right=18)
        self.set_auto_page_break(auto=True, margin=18)

    def header(self):
        if self.page_no() == 1:
            return  # cover page has no running header
        self.set_font("helvetica", "I", 9)
        self.set_text_color(128, 128, 128)
        self.cell(
            0, 5,
            _safe_text(f"Quant Research Scout - {self.scan_date}"),
            align="L",
        )
        self.cell(0, 5, _safe_text(f"Page {self.page_no()}"), align="R", new_x="LMARGIN", new_y="NEXT")
        self.set_text_color(0, 0, 0)
        self.ln(6)

    def footer(self):
        self.set_y(-15)
        self.set_font("helvetica", "I", 8)
        self.set_text_color(160, 160, 160)
        self.cell(0, 5, _safe_text("Generated by cowork_scout"), align="C")
        self.set_text_color(0, 0, 0)


def render_pdf(findings: list[dict], digest: str, out_path: str,
               scan_date: str | None = None) -> str:
    """Build a PDF from this run's findings + digest. Returns absolute path."""
    scan_date = scan_date or date.today().isoformat()
    pdf = _Report(scan_date)

    # ----- Cover -----
    pdf.add_page()
    pdf.set_font("helvetica", "B", 22)
    pdf.cell(0, 12, _safe_text("Quant Research Scout"), new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("helvetica", "", 14)
    pdf.cell(0, 8, _safe_text(f"Daily report - {scan_date}"), new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)
    pdf.set_font("helvetica", "", 11)
    n = len(findings)
    pdf.cell(0, 6,
             _safe_text(f"{n} finding{'s' if n != 1 else ''} saved this run"),
             new_x="LMARGIN", new_y="NEXT")
    pdf.ln(8)

    # ----- Digest -----
    if digest:
        pdf.set_font("helvetica", "B", 14)
        pdf.cell(0, 8, _safe_text("Digest"), new_x="LMARGIN", new_y="NEXT")
        pdf.ln(2)
        pdf.set_font("helvetica", "", 10)
        pdf.multi_cell(0, 5, _safe_text(digest))
        pdf.ln(4)

    if not findings:
        return _finalize(pdf, out_path)

    # ----- Findings -----
    for i, f in enumerate(findings, 1):
        pdf.add_page()

        pdf.set_font("helvetica", "B", 14)
        pdf.multi_cell(0, 7, _safe_text(f"{i}. {f.get('title', '(untitled)')}"))

        pdf.set_font("helvetica", "U", 9)
        pdf.set_text_color(60, 100, 220)
        pdf.cell(0, 5, _safe_text(f.get("url", "")), link=f.get("url", ""),
                 new_x="LMARGIN", new_y="NEXT")
        pdf.set_text_color(0, 0, 0)
        pdf.ln(2)

        pdf.set_font("helvetica", "", 10)
        rel = f.get("relevance")
        rel_s = f"{rel:.2f}" if isinstance(rel, (int, float)) else "?"
        repl = f.get("replicability", 0) or 0
        stars = "*" * int(repl) + "-" * (5 - int(repl))
        meta = (
            f"Source: {f.get('source', '?')}    "
            f"Type: {f.get('edge_type', '?')}    "
            f"Relevance: {rel_s}    "
            f"Replicability: {stars} ({repl}/5)"
        )
        pdf.cell(0, 5, _safe_text(meta), new_x="LMARGIN", new_y="NEXT")
        if f.get("edge_category"):
            pdf.set_font("helvetica", "B", 10)
            pdf.cell(0, 5, _safe_text(f"Edge category: {f['edge_category']}"),
                     new_x="LMARGIN", new_y="NEXT")
            pdf.set_font("helvetica", "", 10)
        if f.get("authors"):
            pdf.cell(0, 5, _safe_text(f"Authors: {f['authors']}"),
                     new_x="LMARGIN", new_y="NEXT")
        if f.get("published"):
            pdf.cell(0, 5, _safe_text(f"Published: {f['published']}"),
                     new_x="LMARGIN", new_y="NEXT")
        pdf.ln(3)

        _section(pdf, "TLDR", f.get("tldr") or "(not provided)")
        _section(pdf, "Summary", f.get("summary") or "")
        _section(pdf, "Key insight", f.get("key_insight") or "", italic=True)
        _section(pdf, "Plain English (ELI5)", f.get("eli5") or "(not provided)")

        tags = (f.get("tags") or []) + (f.get("topic_tags") or [])
        if tags:
            pdf.set_font("helvetica", "I", 9)
            pdf.set_text_color(110, 110, 110)
            pdf.cell(0, 5, _safe_text("Tags: " + ", ".join(tags)),
                     new_x="LMARGIN", new_y="NEXT")
            pdf.set_text_color(0, 0, 0)

    return _finalize(pdf, out_path)


def _section(pdf: _Report, label: str, body: str, italic: bool = False) -> None:
    if not body:
        return
    pdf.set_font("helvetica", "B", 10)
    pdf.cell(0, 6, _safe_text(label), new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("helvetica", "I" if italic else "", 10)
    pdf.multi_cell(0, 5, _safe_text(body))
    pdf.ln(2)


def _finalize(pdf: _Report, out_path: str) -> str:
    out = Path(out_path).resolve()
    out.parent.mkdir(parents=True, exist_ok=True)
    pdf.output(str(out))
    return str(out)
